version: 2.1

executors:
  build-executor:
    docker:
      - image: circleci/android:api-29
    working_directory: ~/flutter-plugins-ci

  android-executor:
    macos:
      xcode: 11.6.0

  ios-executor:
    macos:
      xcode: 11.6.0
    working_directory: ~/flutter-plugins-ci

commands:
  install_flutter:
    description:
      Install Flutter and set up paths.
    parameters:
      flutter_version:
        description: Flutter version
        type: string
        default: stable
    steps:
      - run:
          name: Set up Flutter
          command: |
            echo 'export FLUTTER_HOME=${HOME}/sdks/flutter' >> $BASH_ENV
            echo 'export FLUTTER_VERSION=<< parameters.flutter_version >>' >> $BASH_ENV
            echo 'export FLUTTER_ROOT=${FLUTTER_HOME}' >> $BASH_ENV
            echo 'export PATH=${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:${HOME}/.pub-cache/bin' >> $BASH_ENV
            source $BASH_ENV
            git clone --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}
            (yes || true) | flutter doctor --android-licenses && flutter doctor
  unit_test_flutter:
    description:
      Run flutter unit test on the specified plugin package.
    parameters:
      plugin_name:
        type: string
    steps:
      - run:
          name: Run Flutter unit tests
          command: |
            cd ~/flutter-plugins-ci/packages/<< parameters.plugin_name >>
            flutter test
  unit_test_android:
    description:
      Run Android (Kotlin) unit test on the specified plugin package.
    parameters:
      plugin_name:
        type: string
    steps:
      - run:
          name: Run Android unit tests
          command: |
            cd ~/flutter-plugins-ci/packages/<< parameters.plugin_name >>/example/android
            flutter build apk
            ./gradlew testDebugUnitTest
  unit_test_ios:
    description:
      Run iOS (Swift) unit test on the specified plugin package.
    parameters:
      plugin_name:
        type: string
    steps:
      - run:
          name: Run iOS unit tests
          command: |
            cd ~/flutter-plugins-ci/packages/<< parameters.plugin_name >>/example/ios
            flutter build ios --no-codesign
            xcodebuild test -workspace Runner.xcworkspace -scheme Runner -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6'

jobs:
  unit_test_flutter_battery:
    executor: build-executor
    steps:
      - install_flutter
      - checkout
      - unit_test_flutter:
          plugin_name: battery
  unit_test_android_battery:
    executor: build-executor
    steps:
      - install_flutter
      - checkout
      - unit_test_android:
          plugin_name: battery
  unit_test_ios_battery:
    executor: ios-executor
    steps:
      - install_flutter
      - checkout
      - unit_test_ios:
          plugin_name: battery

releasable_branches: &releasable_branches
  branches:
    only:
      - release
      - master

workflows:
  build_test_deploy:
    jobs:
      - unit_test_flutter_battery
      - unit_test_android_battery
      - unit_test_ios_battery
